2023-03-13 01:01:17,361 [INFO   ] [APP] autotrader started with arguments={-c}
2023-03-13 01:01:17,361 [INFO   ] [APP] configuration={"Execution":{"Host":"172.25.0.2","Port":12345},"Information":{"Type":"mmap","Name":"/info/info.dat"},"TeamName":"LiquidBears_2185","Secret":"fd422f2d93854476adf8328464a29739"}
2023-03-13 01:01:17,464 [INFO   ] [CONNECTION] fd=7 connection established: peer=172.25.0.2:12345
2023-03-13 01:01:35,341 [INFO   ] [TRADER] received order book for instrument 0 with sequence number 1
2023-03-13 01:01:35,341 [INFO   ] [TRADER] SNAPSHOT POSTION 0 HEDGE 0
2023-03-13 01:01:35,341 [INFO   ] [TRADER] CHECKING CURRENT ORDERS TIME TO LIVE!
2023-03-13 01:01:35,341 [INFO   ] [TRADER] NOT DOING ANYTHING HERE BECAUSE INSTRUMENT IS NOT ETF!
2023-03-13 01:01:35,341 [INFO   ] [TRADER] received order book for instrument 1 with sequence number 1
2023-03-13 01:01:35,341 [INFO   ] [TRADER] SNAPSHOT POSTION 0 HEDGE 0
2023-03-13 01:01:35,341 [INFO   ] [TRADER] CHECKING CURRENT ORDERS TIME TO LIVE!
2023-03-13 01:01:35,341 [INFO   ] [TRADER] >>>FIRST ITERATION, DO NOTHING!
2023-03-13 01:01:35,433 [INFO   ] [TRADER] Volume pressure signal is: 1.0
2023-03-13 01:01:35,433 [INFO   ] [TRADER] DECREASING TRADING ACTIVITY DOWN TO 0 ORDERS
2023-03-13 01:01:35,628 [INFO   ] [TRADER] received order book for instrument 0 with sequence number 2
2023-03-13 01:01:35,628 [INFO   ] [TRADER] SNAPSHOT POSTION 0 HEDGE 0
2023-03-13 01:01:35,628 [INFO   ] [TRADER] CHECKING CURRENT ORDERS TIME TO LIVE!
2023-03-13 01:01:35,628 [INFO   ] [TRADER] NOT DOING ANYTHING HERE BECAUSE INSTRUMENT IS NOT ETF!
2023-03-13 01:01:35,628 [INFO   ] [TRADER] received order book for instrument 1 with sequence number 2
2023-03-13 01:01:35,628 [INFO   ] [TRADER] SNAPSHOT POSTION 0 HEDGE 0
2023-03-13 01:01:35,628 [INFO   ] [TRADER] CHECKING CURRENT ORDERS TIME TO LIVE!
2023-03-13 01:01:35,628 [CRITICAL] [TRADER] REAL INTERVAL [126200, 126400] OUR INTERVAL [126000, 126700]
2023-03-13 01:01:35,628 [INFO   ] [TRADER] our interval CONTAINS the actual market interval, TRYING TO TRADE
2023-03-13 01:01:35,628 [ERROR  ] [RECEIVER] connection lost:
Traceback (most recent call last):
  File "/trader_one/ready_trader_go/pubsub.py", line 136, in _subscribe_worker
    protocol.datagram_received(buffer[start:start + length], from_addr)
  File "/trader_one/ready_trader_go/messages.py", line 212, in datagram_received
    self.on_datagram(typ, data, HEADER_SIZE, length)
  File "/trader_one/ready_trader_go/base_auto_trader.py", line 69, in on_datagram
    self.on_order_book_update_message(inst, seq, *BOOK_PART.iter_unpack(data[ORDER_BOOK_HEADER_SIZE:]))
  File "/trader_one/autotrader.py", line 731, in on_order_book_update_message
    self.place_two_orders(new_bid_by_tick, LOT_SIZE, new_ask_by_tick, LOT_SIZE)
  File "/trader_one/autotrader.py", line 336, in place_two_orders
    and self.check_num_operations():
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/trader_one/autotrader.py", line 96, in check_num_operations
    current_time = time()
                   ^^^^
UnboundLocalError: cannot access local variable 'time' where it is not associated with a value
2023-03-13 01:01:35,629 [INFO   ] [APP] closing event loop
2023-03-13 01:01:35,629 [INFO   ] [CONNECTION] fd=7 connection lost
2023-03-13 01:01:35,629 [ERROR  ] [asyncio] Exception in callback _SelectorSocketTransport._call_connection_lost(None)
handle: <Handle _SelectorSocketTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1117, in _call_connection_lost
    super()._call_connection_lost(exc)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 875, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/trader_one/ready_trader_go/base_auto_trader.py", line 59, in connection_lost
    Subscription.close(self)
  File "/trader_one/ready_trader_go/messages.py", line 186, in close
    self._receiver_transport.close()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
